SRCS:=\
    dip_test_score.cpp dip_test_score_client.cpp dip_test_score_client_ut.cpp \
    dip_test_score_ut.cpp isp_test_score.cpp isp_test_score_average.cpp \
    isp_test_score_average_ut.cpp isp_test_score_ut.cpp lsp_test_score.cpp \
    lsp_test_score_ut.cpp ocp_test_score.cpp ocp_test_score_ut.cpp \
    srp_test_score.cpp srp_test_score_ut.cpp

OBJDIR:=
SHARED:=../../deep/
include $(SHARED)make/env.mk
include $(SHARED)make/example.mk
include $(SHARED)make/gtest.mk
