@startditaa
                 緊急度高
                   ^
                   |
      +------------+------------+          
      |            |            |
      |            |            |
      |    第１領域    |    第２領域    | 
      |            |            |
      |        cBLU|cYEL        |
重要度高<-+------------+------------+->重要度低
      |            |            |
      |            |            |
      |    第３領域    |    第４領域    | 
      |            |            |
      |        cGRE|cRED        |
      +------------+------------+
                   |
                   V
                 緊急度低
@endditaa
