@startuml
:初期計画;
note right
    アジャイル系プロセスであっても、ソフトウェアの
    * 機能リスト(重要なユースケース程度)
    * ラフなリリース日程(初期計画)
    は必要。
    イテレーションを繰り返し、理解が進むことにより
    要求仕様や計画を正確にしていく必要がある。
end note

while(開発すべき機能がある?) is (yes)

    partition イテレーション {
        :計画;
            note right
                当イテレーションで開発する機能や
                計画の決定する。
            end note
        :要求分析;
            note right
                全体の要求機能にフィードバック。
            end note
        :設計;
        :コーディング;
            note right
                コーディングと同時に
                * 単体テスト
                * 自動実行が可能な統合テスト
                の実装を行う。
            end note
        :テスト;
            note right
                単体テスト、自動統合テスト、
                自動化できないテストを行う。
            end note
        :振り返り;
            note right
                イテレーションを振り返り、改善する。
                他者に新規機能の評価を行ってもらう。
                全体計画にフィードバックする。
            end note
        }

endwhile (no)

:システムテスト/受入テスト;
:リリース;
@enduml

