@startuml
package Model as ModelPkg {
    class Model {
        notify()
    }

    class Observer {
        Update(Model const&);
    }
}

package Controller as ControllerPkg {
    class Controller
}

package View as ViewPkg {
    class View {
        Update(Model const&);
    }
}

package GuiFrameWork { }

View -up-|> Observer
Model-left->Observer
Controller->Model
View->GuiFrameWork
Controller->GuiFrameWork

@enduml


