@startsalt
{
{T
+project
++app
+++main.cpp
++controller
+++src
++++controller.cpp
+++h
++++controller
+++++controller.h
+++ut
++++controller_ut.cpp
++model
+++h
++++model
+++++model.h
+++++observer.h
+++src
++++model.cpp
++++model_local.h
++++observer.cpp
+++ut
++++model_ut.cpp
++++observer_ut.cpp
++view
+++h
++++view.h
+++src
++++view.cpp
++++view_local.h
+++ut
++++view_ut.cpp
}
}
@endsalt
