@startuml

start

repeat :リポジトリから最新ソースコード入手;
:必要に応じて仕様の理解、詳細設計;
:プログラミング;
:ソースコードのビルドとデプロイ;
:新規ソースコードのテスト;
:新規ソースコード周辺の回帰テスト;
:リポジトリへのソースコードのコミット;

repeat while (実装すべき機能がある?) is (ある)

stop

@enduml


