@startditaa

/-------\                                          next base code
|       |  base code(tag 1.0)                      (tag 2.0)
|master +------\ -=------------------------------------ +-------->
|cBLU   |      |                                        ^
\-------/      |                                        |
               |                                        |
               |                                        |merge
/-------\      |                                test &  |
|       |      |                                bug-fix |
|release+--=-  | -=--------------------------- *--*--*--/ -=----->
|cGRE   |      |                               ^  product release
\-------/      |                               |
               |                               |
               |branch                         |merge
/-------\      |                               |              
|       |      v       branch                  |
|develop+------*---*---+-----+-----*-----*-----/ -=-------------->
|cYEL   |              |     |     ^     ^
\-------/              |     |     |     |
                       |     |  pull-request & merge
                       v     |     |     |
        /---------\ /-----\  |     |     |       
        |         | | xxx +--|-----/     |
        |         | \-----/  v           |   
        |         |       /-----\        |     |
        |features/|       | yyy +--------/     |
        |         |       \-----/              |
        |         |             /-----\        |
        |cRED     |             | ... +-- -=---/
        \---------/             \-----/
@endditaa
