@startuml

package PackageA {
}

package PackageB {
    rectangle "h/PackageB" as h {
        rectangle "B0.h" as B0_h
        rectangle "B3.h" as B3_h
    }

    rectangle "B0.cpp" as B0_cpp
    rectangle "B1.cpp" as B1_cpp
    rectangle "B1.h" as B1_h
    rectangle "B2.cpp" as B2_cpp
    rectangle "B2.h" as B2_h

    package PackageSubB {
    }
}

package PackageC {
}

B0_cpp -up-> B0_h
B0_cpp -up-> B1_h
B0_cpp -up-> B2_h
B1_cpp -up-> B1_h
B1_cpp -down-> PackageSubB
B2_cpp -up-> B2_h
B2_cpp -down-> PackageSubB

note top of h
h/PackageBに入っている
ヘッダファイルのみが
外部公開される
end note

note "外部公開ヘッダファイル" as N2

B0_h .up. N2
B3_h .up. N2

note "外部非公開ヘッダファイル" as N1

B1_h .up. N1
B2_h .up. N1

PackageA<-down--PackageB
PackageB<-down--PackageC

@enduml
