@startditaa

+----+                                                        +-----+
|    |                                                        |     |
|要件分析| <-=--------------------------------------------------> |受入テスト|
|cRED|                                                        |cRED |
+--+-+                                                        +--+--+
   |                                                             ^
   |  +----+                                           +-------+ |
   |  |    |                                           |       | |
   +->|基本設計| <-=-------------------------------------> |システムテスト+-+
      |cBLU|                                           |cBLU   |
      +--+-+                                           +---+---+
         |                                                 ^
         |   +----+                             +-----+    |
         |   |    |                             |     |    |
         +-->|機能設計| <-=-----------------------> |結合テスト+----+
             |cGRE|                             |cGRE |
             +--+-+                             +--+--+
                |                                  ^
                |    +----+              +-----+   |
                |    |    |              |     |   |
                +--->|詳細設計| <-=--------> |単体テスト+---+
                     |cPNK|              |cPNK |
                     +--+-+              +--+--+
                        |                   ^
                        |      +------+     |
                        |      |      |     |
                        +----->|コーディング+-----+
                               |      |
                               +------+

'日本語でカラムがずれる
@endditaa
