@startditaa

  Waterfall    |                       Iterative(スクラム等)
               | +---------------------------------------------------------------|
+-----------+  | |                         Iteration 0                           |
|           |  | |  +-----------+  +-----------+  +-----------+  +------------+  |
|Requirement|  | |  |Requirement|->| Designing |->| Coding/UT |->|   IT/ST    |  |
|   c8F8    |  | |  |    c8F8   |  |    c8D8   |  |   c898    |  |    c868    |  |
+-----+-----+  | |  +-----------+  +-----------+  +-----------+  +------------+  |
      |        | |---------------------------------------------------------------+
      |        |                               | | |
      |        |                               v v v
      v        | +---------------------------------------------------------------|
+-----------+  | |                         Iteration 1                           |
|           |  | |  +-----------+  +-----------+  +-----------+  +------------+  |
| Designing |  | |  |Requirement|->| Designing |->| Coding/UT |->|   IT/ST    |  |
|   c8D8    |  | |  |    c8F8   |  |    c8D8   |  |   c898    |  |    c868    |  |
+-----+-----+  | |  +-----------+  +-----------+  +-----------+  +------------+  |
      |        | |---------------------------------------------------------------+
      |        |                               | | |                                                                                                                                   +----------------------------------------------------------------                                                                  +----------------------------------------------------------------
      v        |                               v v v                                                                                                                                   
+-----------+  |
|           |  |                                    
| Coding/UT |  |                           Iterationの繰り返し
|   c898    |  |
+-----+-----+  |
      |        |                               | | |
      |        |                               v v v
      v        | +---------------------------------------------------------------|
+-----------+  | |                         Iteration N                           | 
|           |  | |  +-----------+  +-----------+  +-----------+  +------------+  | 
|   IT/ST   |  | |  |Requirement|->| Designing |->| Coding/UT |->|   IT/ST    |  | 
|   c868    |  | |  |    c8F8   |  |    c8D8   |  |   c898    |  |    c868    |  | 
+-----------+  | |  +-----------+  +-----------+  +-----------+  +------------+  | 
               | |---------------------------------------------------------------+ 

@endditaa
