SRCS:=model.cpp view.cpp controller.cpp model_ut.cpp view_ut.cpp controller_ut.cpp 
SRCS2:=main.cpp model.cpp view.cpp controller.cpp 

SHARED:=../../../shared/
include $(SHARED)make/env.mk
include $(SHARED)make/example.mk
include $(SHARED)make/gtest.mk
