SRCS:=\
    class_ut.cpp etc.cpp float_ut.cpp func_ut.cpp \
    header_ut.cpp lib/header.cpp operator_ut.cpp preprocessor_ut.cpp runtime_ut.cpp scope_ut.cpp \
    scoped_guard_ut.cpp string_vector.cpp string_view_ut.cpp syntax_ut.cpp type_ut.cpp \
	type_const_ut.cpp pkg.cpp raw_literal_ut.cpp

OBJDIR:=
SHARED:=../../essential/
include $(SHARED)make/env.mk
include $(SHARED)make/example.mk
include $(SHARED)make/gtest.mk
