SRCS:=model_ut.cpp view_ut.cpp controller_ut.cpp model.cpp view.cpp controller.cpp 
SRCS2:=main.cpp model.cpp view.cpp controller.cpp 

OBJDIR:=
SHARED:=../../essential/
include $(SHARED)make/env.mk
include $(SHARED)make/example.mk
include $(SHARED)make/gtest.mk
