SRCS:=\
    accessor.cpp clone.cpp copy_and_swap.cpp di.cpp enum_bitmask.cpp factory_lib.cpp factory.cpp \
    future.cpp guard.cpp immutable.cpp named_constructor_lib.cpp named_constructor.cpp \
    null_object.cpp nvi.cpp observer.cpp pimpl.cpp proxy.cpp raii.cpp singleton.cpp state.cpp \
    strategy.cpp template_method.cpp visitor.cpp crtp.cpp \

OBJDIR:=
SHARED:=../../essential/
include $(SHARED)make/env.mk
include $(SHARED)make/example.mk
include $(SHARED)make/gtest.mk
