マークダウンに<img src="data:image/png;base64, ...>
を埋め込むとAIによるレビューをしようとすると、
そのセッションがストールしてしまいレビューができなくなる。

マークダウンに<img src="data:image/png;base64, ...>
を埋め込む代わりに、わりに下記のようなコードを埋め込む仕様とした。

    ```plantuml
        plant umlのソースコード
    ```
